default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/blocipedia_development
  host: localhost

test:
  <<: *default
  database: db/blocipedia_test

production:
  <<: *default
  database: db/blocipedia_production
